### ISSUE TITLE
coerce rules for subdocuments add coerced field and value to top level document

### ISSUE THREAD

**Issue by derek-miller** [nicolaiarocci/cerberus#252]
```python
>>> import cerberus
>>> v = cerberus.Validator(schema={'dict_a': {'type': 'dict', 'schema': {'field_a': {'type': 'string', 'coerce': lambda value: str(value)}}}})
>>> v.validate({'dict_a': {'field_a': 1}})
True
>>> v.document
{'dict_a': {'field_a': 1}, 'field_a': '1'}
```

I am happy to submit a fix for this if this is considered a use case cerberus should support.

Edit:
I am running version 0.9.2

**Comment by derek-miller** [comment]
Just saw that this is fixed in master. Do you know when you will be releasing v1.0?

**Comment by nicolaiarocci** [comment]
Hello. There's a bug still one bug on the [1.0 roadmap](https://github.com/nicolaiarocci/cerberus/milestone/1), and then we're good to go!

**Comment by sybrenstuvel** [comment]
This is still an issue in 0.9.2, which is the latest version usable with the latest release of Eve. Is this going to be backported and released as 0.9.3? This diff is enough to fix it:

```
diff --git a/cerberus/cerberus.py b/cerberus/cerberus.py
index 8bca78f..52b8753 100644
--- a/cerberus/cerberus.py
+++ b/cerberus/cerberus.py
@@ -312,7 +312,7 @@ class Validator(object):
         if 'coerce' in definition:
             value = self._validate_coerce(definition['coerce'], field,
                                           value)
-            self.document[field] = value
+            self.current[field] = value
 
         if 'readonly' in definition:
             self._validate_readonly(definition['readonly'], field,
```
