### ISSUE TITLE
`readonly` param designed behaviour is broken with `oneof`, `anyof`

### ISSUE THREAD

**Issue by rredkovich** [nicolaiarocci/cerberus#297]
#### Use-case abstract

According to docs `readonly` parameter [should give False](http://docs.python-cerberus.org/en/stable/validation-rules.html#readonly) on validation if field with that parameter is in dict.

Works as expected in general case:
```python
import cerberus

schema_one = {
    'id': {'type': 'integer', 'readonly': True},
    'text': {'type': 'string', 'required': True}
}
schema_two = {
    'id': {'type': 'integer', 'readonly': True},
    'extra_text': {'type': 'string', 'required': True}
}

v = cerberus.Validator({'record': {'type': 'dict', 'schema': schema_one}})

test_data = {'record': {'id': 10, 'text': 'ooops'}}
v.validate(test_data)
# -> False
v.errors
# -> {'record': [{'id': ['field is read-only']}]}
```

----

#### Support request / Bug report
However using multiple schemas with `oneof` for field will produce unexpected `True`.

```python
import cerberus

schema_one = {
    'id': {'type': 'integer', 'readonly': True},
    'text': {'type': 'string', 'required': True}
}
schema_two = {
    'id': {'type': 'integer', 'readonly': True},
    'extra_text': {'type': 'string', 'required': True}
}

v = cerberus.Validator({'record': {'type': 'dict', 'oneof_schema': [schema_one, schema_two]}})

test_data = {'record': {'id': 10, 'text': 'ooops'}}
v.validate(test_data)
# -> True
v.errors
# -> {}
```
`anyof` gives same result, not tested with `noneof` and `allof`.
Bug exists in version 1.1, 1.0.x, in 9.x exception is raised when using `readonly` param.

**Comment by funkyfuture** [comment]
i pledge to mark this for the `1.2` milestone.

**Comment by funkyfuture** [comment]
solving this for one of the rules should solve it for all as the subvalidation dispatching is the same.

@dkellner, if i'm not wrong you could be able to give competent guidance on this issue, iirc you implemented the conjunction of normalization and validation for the readonly rule.

**Comment by dkellner** [comment]
Yes, it was in PR #282. The other (non-simple) fix we had for that is in #272, and I still have the branch here: https://github.com/dkellner/cerberus/tree/default-readonly .

IIRC and Cerberus still works the same internally, we're doing two full traversals now: one for normalization, and one for validation (more details in e.g. https://github.com/pyeve/cerberus/issues/268#issuecomment-248239479). `readonly` is special in that: it's a validation rule that needs to be performed before normalization because it should see the original document before any modifcation happened. Unfortunately you cannot easily traverse the document for just `readonly` (that is exactly why I've implemented the `rule_filter` in #272).

Unfortunately I cannot look deeper into this now as lunar new year is coming. Let me know if I can still be of help in about two weeks.

**Comment by funkyfuture** [comment]
> we're doing two full traversals now: one for normalization, and one for validation

and i want to point out that the two traversals are different and that itches me because it complicates things, but there seems no sane way around it.

anyway, has someone the time to tackle this bug? it's the hardest nut on the [1.3](https://github.com/pyeve/cerberus/milestone/6) playlist so far.

**Comment by dkellner** [comment]
> anyway, has someone the time to tackle this bug? it's the hardest nut on the 1.3 playlist so far.

I'm afraid I will not find the time for that the coming weeks. There are still some "urgent" issues in Eve-SQLAlchemy I'd have to tackle first and that's progressing rather slowly already...

> and i want to point out that the two traversals are different and that itches me because it complicates things, but there seems no sane way around it.

I'd argue the very nature of normalization and validation are different. If we're not doing a clear separation we will run in all kind of interesting bugs as the document keeps changing at a stage (validation) we're not expecting that anymore. And with `readonly` we actually need three traversals: pre-normalization-validation (`readonly`), normalization, post-normalization-validation (most rules).

**Comment by funkyfuture** [comment]
> I'd argue the very nature of normalization and validation are different. If we're not doing a clear separation we will run in all kind of interesting bugs

that is more or less my point. the thing is, the code is very prone to bugs, though the processing stages are seperated clearly and because the user interface happens to expose rules and interdependencies of such across the stages. but we wouldn't want to change the simplicity of the interface that is provided by this. i just feel the urge to re-iterate often enough that each design decision and implementation detail that touches these circumstances must be well reasoned and that it all has its limits.

the `readonly` rule will actually be a good test of this [proposed design](#372), it may prove it to be unfit or provide the ground for a cleaner solution.

**Comment by funkyfuture** [comment]
unless there are other proposals how to proceed with this issue, i'm going to remove the `1.3` milestone from this.
